import Program from '#models/program'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  async run() {
    await Program.createMany([
      {
        name: 'Kelas Perbaikan Sepeda',
        description:
          'Belajar memperbaiki sepeda dan menggunakan alat bengkel sederhana, cocok untuk calon mekanik.',
        realistic: 0.9,
        investigative: 0.3,
        artistic: 0.05,
        social: 0.1,
        enterprising: 0.15,
        conventional: 0.3,
      },
      {
        name: 'Workshop Kerajinan Kayu',
        description:
          'Membuat kerajinan sederhana seperti rak atau kotak dari kayu, mengasah keterampilan tukang.',
        realistic: 0.85,
        investigative: 0.2,
        artistic: 0.2,
        social: 0.1,
        enterprising: 0.15,
        conventional: 0.25,
      },
      {
        name: 'Eksperimen Sains Sederhana',
        description:
          'Melakukan eksperimen seperti membuat roket air atau larutan kimia aman untuk calon peneliti.',
        realistic: 0.3,
        investigative: 0.9,
        artistic: 0.1,
        social: 0.2,
        enterprising: 0.1,
        conventional: 0.4,
      },
      {
        name: 'Klub Pengamatan Alam',
        description:
          'Mengamati tumbuhan dan serangga di sekitar pondok, cocok untuk pecinta biologi.',
        realistic: 0.35,
        investigative: 0.85,
        artistic: 0.15,
        social: 0.25,
        enterprising: 0.1,
        conventional: 0.35,
      },
      {
        name: 'Lukis Mural Komunitas',
        description:
          'Menggambar mural di dinding pondok untuk mengembangkan kreativitas dan kerja tim.',
        realistic: 0.2,
        investigative: 0.1,
        artistic: 0.9,
        social: 0.4,
        enterprising: 0.3,
        conventional: 0.15,
      },
      {
        name: 'Kelas Menggambar Sketsa',
        description: 'Belajar teknik menggambar sketsa dan poster, ideal untuk calon desainer.',
        realistic: 0.15,
        investigative: 0.1,
        artistic: 0.95,
        social: 0.3,
        enterprising: 0.25,
        conventional: 0.1,
      },
      {
        name: 'Kerajinan Daur Ulang',
        description:
          'Membuat kerajinan dari bahan bekas seperti botol atau kain untuk calon seniman.',
        realistic: 0.25,
        investigative: 0.15,
        artistic: 0.9,
        social: 0.35,
        enterprising: 0.2,
        conventional: 0.2,
      },
      {
        name: 'Kelas Musik Ukulele',
        description: 'Belajar memainkan ukulele dan lagu sederhana, cocok untuk pecinta musik.',
        realistic: 0.1,
        investigative: 0.05,
        artistic: 0.9,
        social: 0.4,
        enterprising: 0.25,
        conventional: 0.15,
      },
      {
        name: 'Kegiatan Amal Lingkungan',
        description: 'Membersihkan lingkungan sekitar pondok, mengasah kepedulian sosial.',
        realistic: 0.15,
        investigative: 0.2,
        artistic: 0.1,
        social: 0.9,
        enterprising: 0.3,
        conventional: 0.25,
      },
      {
        name: 'Kelas Mengajar Teman',
        description:
          'Melatih keterampilan mengajar dengan berbagi pengetahuan kepada teman sebaya.',
        realistic: 0.05,
        investigative: 0.25,
        artistic: 0.2,
        social: 0.95,
        enterprising: 0.4,
        conventional: 0.2,
      },
      {
        name: 'Diskusi Kelompok',
        description:
          'Memimpin diskusi tentang topik kehidupan sehari-hari, cocok untuk calon konselor.',
        realistic: 0.05,
        investigative: 0.3,
        artistic: 0.15,
        social: 0.9,
        enterprising: 0.35,
        conventional: 0.2,
      },
      {
        name: 'Doa dan Refleksi Bersama',
        description:
          'Mengorganisir doa kelompok dan refleksi, meng EMBED keterampilan kepemimpinan sosial.',
        realistic: 0.05,
        investigative: 0.1,
        artistic: 0.2,
        social: 0.95,
        enterprising: 0.4,
        conventional: 0.25,
      },
      {
        name: 'Simulasi Usaha Kecil',
        description:
          'Merancang usaha kecil seperti jualan makanan ringan, cocok untuk calon pengusaha.',
        realistic: 0.15,
        investigative: 0.25,
        artistic: 0.2,
        social: 0.4,
        enterprising: 0.9,
        conventional: 0.5,
      },
      {
        name: 'Kelas Public Speaking',
        description: 'Berlatih berbicara di depan umum untuk membangun kepercayaan diri.',
        realistic: 0.05,
        investigative: 0.2,
        artistic: 0.3,
        social: 0.5,
        enterprising: 0.95,
        conventional: 0.3,
      },
      {
        name: 'Pengelolaan Acara Pondok',
        description:
          'Mengatur acara seperti lomba atau perayaan, melatih kepemimpinan dan organisasi.',
        realistic: 0.1,
        investigative: 0.25,
        artistic: 0.25,
        social: 0.5,
        enterprising: 0.9,
        conventional: 0.4,
      },
      {
        name: 'Kelas Pemasaran Sederhana',
        description:
          'Belajar membuat iklan sederhana untuk produk lokal, cocok untuk calon marketer.',
        realistic: 0.1,
        investigative: 0.3,
        artistic: 0.35,
        social: 0.4,
        enterprising: 0.9,
        conventional: 0.35,
      },
      {
        name: 'Pengelolaan Jadwal',
        description: 'Menyusun jadwal kegiatan pondok, melatih keterampilan administrasi.',
        realistic: 0.05,
        investigative: 0.3,
        artistic: 0.05,
        social: 0.1,
        enterprising: 0.2,
        conventional: 0.95,
      },
      {
        name: 'Pencatatan Inventaris',
        description: 'Mengelola daftar peralatan pondok, cocok untuk calon bendahara.',
        realistic: 0.1,
        investigative: 0.35,
        artistic: 0.05,
        social: 0.15,
        enterprising: 0.2,
        conventional: 0.9,
      },
      {
        name: 'Kelas Penganggaran',
        description:
          'Belajar membuat anggaran sederhana untuk kegiatan, ideal untuk calon akuntan.',
        realistic: 0.05,
        investigative: 0.4,
        artistic: 0.05,
        social: 0.1,
        enterprising: 0.25,
        conventional: 0.95,
      },
      {
        name: 'Pengelolaan Data Sederhana',
        description: 'Menggunakan spreadsheet untuk mengatur data, cocok untuk calon analis data.',
        realistic: 0.1,
        investigative: 0.45,
        artistic: 0.05,
        social: 0.15,
        enterprising: 0.2,
        conventional: 0.9,
      },
    ])
  }
}
